// Real data extracted from .antigravity/team/shared/advanced_quality_results.json
// Generated 2026-04-23. Pipeline v3.0, run_id: 20260423_163006

import WEIGHTS from "./quality_weights.json";

export const PORTAL_STATS = {
  totalDatasets: 290,
  avgScore: 88.83,
  totalOrgs: 65,
  goldDatasets: 189,
  silverDatasets: 80,
  bronzeDatasets: 19,
  goldOrgs: 33,
  silverOrgs: 31,
  bronzeOrgs: 1,
  snapshotDate: "2026-04-23",
  evaluationDate: "2026-04-23",
} as const;

export type Grade = "Gold" | "Silver" | "Bronze";

export interface OrgRanking {
  name: string;
  nameEn: string;
  datasets: number;
  score: number;
  grade: Grade;
}

// Top organizations by average score (real data)
export const ORG_RANKINGS: OrgRanking[] = [
  { name: "Universidad de Ciencias de la Seguridad", nameEn: "Universidad de Ciencias de la Seguridad", datasets: 2, score: 96.2, grade: "Gold" },
  { name: "Junta Local de Conciliación y Arbitraje", nameEn: "Junta Local de Conciliación y Arbitraje", datasets: 2, score: 96.0, grade: "Gold" },
  { name: "Oficina de Comunicación del Ejecutivo del Estado", nameEn: "Oficina de Comunicación del Ejecutivo del Estado", datasets: 2, score: 95.8, grade: "Gold" },
  { name: "Instituto de Movilidad y Accesibilidad", nameEn: "Instituto de Movilidad y Accesibilidad", datasets: 10, score: 94.4, grade: "Gold" },
  { name: "Secretaría de Salud", nameEn: "Secretaría de Salud", datasets: 29, score: 94.1, grade: "Gold" },
  { name: "Fideicomiso para el Desarrollo del Sur del Estado de Nuevo León", nameEn: "Fideicomiso para el Desarrollo del Sur del Estado de Nuevo León", datasets: 6, score: 94.1, grade: "Gold" },
  { name: "Secretaría de Desarrollo Regional y Agropecuario", nameEn: "Secretaría de Desarrollo Regional y Agropecuario", datasets: 4, score: 94.1, grade: "Gold" },
  { name: "Servicios de Agua y Drenaje de Monterrey, I.P.D.", nameEn: "Servicios de Agua y Drenaje de Monterrey, I.P.D.", datasets: 8, score: 94.0, grade: "Gold" },
  { name: "Instituto de Investigación, Innovación y Estudios de Posgrado para la Educación del Estado de Nuevo León", nameEn: "Instituto de Investigación, Innovación y Estudios de Posgrado para la Educación del Estado de Nuevo León", datasets: 2, score: 93.9, grade: "Gold" },
  { name: "Instituto Registral y Catastral del Estado de Nuevo León", nameEn: "Instituto Registral y Catastral del Estado de Nuevo León", datasets: 2, score: 93.6, grade: "Gold" },
  { name: "Instituto de la Vivienda", nameEn: "Instituto de la Vivienda", datasets: 2, score: 93.6, grade: "Gold" },
  { name: "Instituto Estatal de las Personas Adultas Mayores (IEPAM)", nameEn: "Instituto Estatal de las Personas Adultas Mayores (IEPAM)", datasets: 2, score: 93.4, grade: "Gold" },
  { name: "Fideicomiso BP3417 CENDIS", nameEn: "Fideicomiso BP3417 CENDIS", datasets: 2, score: 93.4, grade: "Gold" },
  { name: "Instituto de Capacitación y Educación para el Trabajo (ICET)", nameEn: "Instituto de Capacitación y Educación para el Trabajo (ICET)", datasets: 2, score: 93.2, grade: "Gold" },
  { name: "Secretaría de las Mujeres", nameEn: "Secretaría de las Mujeres", datasets: 2, score: 93.0, grade: "Gold" },
  { name: "Secretaría Ejecutiva del Sistema Estatal Anticorrupción del Estado de Nuevo León (SESEANL)", nameEn: "Secretaría Ejecutiva del Sistema Estatal Anticorrupción del Estado de Nuevo León (SESEANL)", datasets: 6, score: 92.9, grade: "Gold" },
  { name: "Sistema Integral para el Manejo Ecológico y Procesamiento de Desechos (SIMEPRODE)", nameEn: "Sistema Integral para el Manejo Ecológico y Procesamiento de Desechos (SIMEPRODE)", datasets: 2, score: 92.7, grade: "Gold" },
  { name: "Colegio de Estudios Científicos y Tecnológicos del Estado de Nuevo León (CECyTENL)", nameEn: "Colegio de Estudios Científicos y Tecnológicos del Estado de Nuevo León (CECyTENL)", datasets: 2, score: 92.5, grade: "Gold" },
  { name: "Parque Fundidora, O.P.D", nameEn: "Parque Fundidora, O.P.D", datasets: 2, score: 92.2, grade: "Gold" },
  { name: "Fideicomiso FIDEURB (BP6823)", nameEn: "Fideicomiso FIDEURB (BP6823)", datasets: 2, score: 91.8, grade: "Gold" },
  { name: " Secretaría de Economía", nameEn: " Secretaría de Economía", datasets: 2, score: 91.7, grade: "Gold" },
  { name: "Secretaría de Igualdad e Inclusión", nameEn: "Secretaría de Igualdad e Inclusión", datasets: 14, score: 91.7, grade: "Gold" },
  { name: "Universidad Tecnológica Gral. Mariano Escobedo", nameEn: "Universidad Tecnológica Gral. Mariano Escobedo", datasets: 2, score: 91.7, grade: "Gold" },
  { name: "Consejo para la Cultura y las Artes de Nuevo León", nameEn: "Consejo para la Cultura y las Artes de Nuevo León", datasets: 2, score: 91.7, grade: "Gold" },
  { name: "Secretaría Técnica de Gobierno", nameEn: "Secretaría Técnica de Gobierno", datasets: 3, score: 91.6, grade: "Gold" },
  { name: "Universidad Tecnológica Linares", nameEn: "Universidad Tecnológica Linares", datasets: 2, score: 91.4, grade: "Gold" },
  { name: "Instituto Constructor de Infraestructura Física Educativa y Deportiva", nameEn: "Instituto Constructor de Infraestructura Física Educativa y Deportiva", datasets: 2, score: 91.3, grade: "Gold" },
  { name: "Fideicomiso Fondo de Fomento Agropecuario del Estado de Nuevo León", nameEn: "Fideicomiso Fondo de Fomento Agropecuario del Estado de Nuevo León", datasets: 2, score: 90.9, grade: "Gold" },
  { name: "Secretaría de Medio Ambiente", nameEn: "Secretaría de Medio Ambiente", datasets: 4, score: 90.7, grade: "Gold" },
  { name: "Sistema de Transporte Colectivo Metrorrey", nameEn: "Sistema de Transporte Colectivo Metrorrey", datasets: 6, score: 90.5, grade: "Gold" },
  { name: "Instituto del Agua del Estado de Nuevo León", nameEn: "Instituto del Agua del Estado de Nuevo León", datasets: 2, score: 90.3, grade: "Gold" },
  { name: "Secretaría de Movilidad y Planeación Urbana", nameEn: "Secretaría de Movilidad y Planeación Urbana", datasets: 2, score: 90.3, grade: "Gold" },
  { name: "Colegio Militarizado \"General Mariano Escobedo\"", nameEn: "Colegio Militarizado \"General Mariano Escobedo\"", datasets: 2, score: 90.2, grade: "Gold" },
  { name: "Fideicomiso Turismo Nuevo León", nameEn: "Fideicomiso Turismo Nuevo León", datasets: 2, score: 90.0, grade: "Silver" },
  { name: "Servicios de salud de Nuevo León, O.P.D.", nameEn: "Servicios de salud de Nuevo León, O.P.D.", datasets: 2, score: 89.9, grade: "Silver" },
  { name: "Sistema de Radio y Televisión de Nuevo León", nameEn: "Sistema de Radio y Televisión de Nuevo León", datasets: 2, score: 89.5, grade: "Silver" },
  { name: "Fideicomiso Fondo para la Vivienda de los Trabajadores de la Educación y el Estado (FOVILEON)", nameEn: "Fideicomiso Fondo para la Vivienda de los Trabajadores de la Educación y el Estado (FOVILEON)", datasets: 4, score: 89.2, grade: "Silver" },
  { name: "Fideicomiso de Proyectos Estratégicos (FIDEPROES)", nameEn: "Fideicomiso de Proyectos Estratégicos (FIDEPROES)", datasets: 2, score: 89.1, grade: "Silver" },
  { name: "Instituto Estatal de las Mujeres", nameEn: "Instituto Estatal de las Mujeres", datasets: 2, score: 89.0, grade: "Silver" },
  { name: "Contraloría y Transparencia Gubernamental", nameEn: "Contraloría y Transparencia Gubernamental", datasets: 4, score: 88.9, grade: "Silver" },
  { name: "Instituto Estatal de Cultura Física y Deporte (INDE)", nameEn: "Instituto Estatal de Cultura Física y Deporte (INDE)", datasets: 6, score: 88.8, grade: "Silver" },
  { name: "Promotora de Desarrollo Rural de Nuevo León – PRODERLEON", nameEn: "Promotora de Desarrollo Rural de Nuevo León – PRODERLEON", datasets: 2, score: 88.4, grade: "Silver" },
  { name: "Oficina de Representación del Estado en la Ciudad de Mexico", nameEn: "Oficina de Representación del Estado en la Ciudad de Mexico", datasets: 2, score: 88.4, grade: "Silver" },
  { name: "Sistema de Caminos de Nuevo León", nameEn: "Sistema de Caminos de Nuevo León", datasets: 2, score: 88.0, grade: "Silver" },
  { name: "Instituto de Innovación y Transferencia Tecnológica de Nuevo León", nameEn: "Instituto de Innovación y Transferencia Tecnológica de Nuevo León", datasets: 2, score: 88.0, grade: "Silver" },
  { name: "Secretaría de Turismo", nameEn: "Secretaría de Turismo", datasets: 5, score: 88.0, grade: "Silver" },
  { name: "Centro Estatal de Becas", nameEn: "Centro Estatal de Becas", datasets: 2, score: 87.8, grade: "Silver" },
  { name: "Fideicomiso Fondo de Apoyo para la Creación y Consolidación del Empleo Productivo en el Estado de Nuevo León (FOCRECE)", nameEn: "Fideicomiso Fondo de Apoyo para la Creación y Consolidación del Empleo Productivo en el Estado de Nuevo León (FOCRECE)", datasets: 2, score: 87.0, grade: "Silver" },
  { name: "Secretaría de Administración", nameEn: "Secretaría de Administración", datasets: 18, score: 86.9, grade: "Silver" },
  { name: "Centro de Conciliación Laboral", nameEn: "Centro de Conciliación Laboral", datasets: 2, score: 86.8, grade: "Silver" },
  { name: "Secretaría de Participación Ciudadana", nameEn: "Secretaría de Participación Ciudadana", datasets: 40, score: 86.8, grade: "Silver" },
  { name: "Secretaría de Seguridad", nameEn: "Secretaría de Seguridad", datasets: 16, score: 86.5, grade: "Silver" },
  { name: "Instituto de Defensoría Pública de Nuevo León", nameEn: "Instituto de Defensoría Pública de Nuevo León", datasets: 2, score: 86.4, grade: "Silver" },
  { name: "Fideicomiso de Inversión y Administración (FIDEMEJORA)", nameEn: "Fideicomiso de Inversión y Administración (FIDEMEJORA)", datasets: 2, score: 86.1, grade: "Silver" },
  { name: "Corporación para el Desarrollo Turístico de Nuevo León", nameEn: "Corporación para el Desarrollo Turístico de Nuevo León", datasets: 2, score: 85.9, grade: "Silver" },
  { name: "Fideicomiso para el Reordenamiento Comercial (FIRECOM)", nameEn: "Fideicomiso para el Reordenamiento Comercial (FIRECOM)", datasets: 2, score: 84.3, grade: "Silver" },
  { name: "Fideicomiso Para el Desarrollo de la Zona Citrícola", nameEn: "Fideicomiso Para el Desarrollo de la Zona Citrícola", datasets: 2, score: 83.4, grade: "Silver" },
  { name: "Fideicomiso No. 2284 \"Tren Suburbano Villa García-Aeropuerto de Monterrey, Primera fase, Etapa 1\"", nameEn: "Fideicomiso No. 2284 \"Tren Suburbano Villa García-Aeropuerto de Monterrey, Primera fase, Etapa 1\"", datasets: 2, score: 76.0, grade: "Silver" },
  { name: "Secretaría de Cultura", nameEn: "Secretaría de Cultura", datasets: 5, score: 75.9, grade: "Silver" },
  { name: "Fideicomiso No. 2209 \"Línea 3 del Sistema de Transporte Colectivo Metrorrey\"", nameEn: "Fideicomiso No. 2209 \"Línea 3 del Sistema de Transporte Colectivo Metrorrey\"", datasets: 2, score: 75.7, grade: "Silver" },
  { name: "Sistema Estatal de Información", nameEn: "Sistema Estatal de Información", datasets: 2, score: 75.3, grade: "Silver" },
  { name: "Fideicomiso para la Conservación del Patrimonio Cultural de Nuevo León (FIDECULTURAL)", nameEn: "Fideicomiso para la Conservación del Patrimonio Cultural de Nuevo León (FIDECULTURAL)", datasets: 2, score: 75.2, grade: "Silver" },
  { name: "Secretaría de Educación del Estado de Nuevo León", nameEn: "Secretaría de Educación del Estado de Nuevo León", datasets: 8, score: 74.7, grade: "Silver" },
  { name: "Oficina Ejecutiva del Titular del Poder Ejecutivo del Estado de Nuevo León", nameEn: "Oficina Ejecutiva del Titular del Poder Ejecutivo del Estado de Nuevo León", datasets: 2, score: 71.4, grade: "Silver" },
  { name: "Fondo Editorial de Nuevo León", nameEn: "Fondo Editorial de Nuevo León", datasets: 2, score: 64.2, grade: "Bronze" },
];

// 7 dimensiones — pesos desde quality_weights.json (fuente canónica; sincronizar con scripts/sync_weights.py)
export const ISO_DIMENSIONS = [
  {
    id: "completeness",
    nameEs: "Completitud",
    nameEn: "Completeness",
    weight: WEIGHTS.completeness,
    icon: "CheckSquare",
    descriptionEs: "Proporción de valores no nulos sobre el total de celdas esperadas en el dataset.",
    descriptionEn: "Ratio of non-null values over the total expected cells in the dataset.",
    formulaEs: "Celdas completas ÷ Total celdas × 100",
    formulaEn: "Complete cells ÷ Total cells × 100",
    exampleEs: "Solicitudes de Acceso a la Información — 13 columnas, 100% sin nulos.",
    exampleEn: "Public Information Requests — 13 columns, 100% non-null.",
    isoRef: "ISO/IEC 25012:2008 §4.14",
  },
  {
    id: "accuracy",
    nameEs: "Exactitud",
    nameEn: "Accuracy",
    weight: WEIGHTS.accuracy,
    icon: "Crosshair",
    descriptionEs: "Grado en que los valores del dataset representan correctamente el fenómeno real que describen.",
    descriptionEn: "Degree to which dataset values correctly represent the real-world phenomenon they describe.",
    formulaEs: "Penalización por discrepancias detectadas entre valores y metadatos esperados.",
    formulaEn: "Penalty for discrepancies detected between values and expected metadata.",
    exampleEs: "Fechas futuras en columnas históricas → penalización de exactitud.",
    exampleEn: "Future dates in historical columns → accuracy penalty.",
    isoRef: "ISO/IEC 25012:2008 §4.10",
  },
  {
    id: "consistency",
    nameEs: "Consistencia",
    nameEn: "Consistency",
    weight: WEIGHTS.consistency,
    icon: "Layers",
    descriptionEs: "Ausencia de contradicciones entre valores del mismo dataset o entre datasets relacionados.",
    descriptionEn: "Absence of contradictions between values in the same dataset or related datasets.",
    formulaEs: "Proporción de registros sin violaciones de reglas de dominio o integridad.",
    formulaEn: "Proportion of records without domain or integrity rule violations.",
    exampleEs: "Columna 'sexo' con valores M/F/m/f sin normalizar → baja consistencia.",
    exampleEn: "Column 'sexo' with M/F/m/f without normalisation → low consistency.",
    isoRef: "ISO/IEC 25012:2008 §4.11",
  },
  {
    id: "documentation",
    nameEs: "Documentación",
    nameEn: "Documentation",
    weight: WEIGHTS.documentation,
    icon: "FileText",
    descriptionEs: "Presencia de título, descripción, licencia, organización y frecuencia de actualización en los metadatos CKAN.",
    descriptionEn: "Presence of title, description, license, organization, and update frequency in CKAN metadata.",
    formulaEs: "Σ campos presentes × peso_campo ÷ peso_máximo × 100",
    formulaEn: "Σ present fields × field_weight ÷ max_weight × 100",
    exampleEs: "Dataset sin licencia explícita → descuento de 20 puntos.",
    exampleEn: "Dataset without explicit license → 20-point deduction.",
    isoRef: "ISO/IEC 25012:2008 §4.13",
  },
  {
    id: "uniqueness",
    nameEs: "Unicidad",
    nameEn: "Uniqueness",
    weight: WEIGHTS.uniqueness,
    icon: "Fingerprint",
    descriptionEs: "Grado en que cada entidad del dataset aparece una sola vez, sin registros duplicados.",
    descriptionEn: "Degree to which each entity in the dataset appears only once, without duplicate records.",
    formulaEs: "1 − (filas_duplicadas ÷ total_filas) × 100",
    formulaEn: "1 − (duplicate_rows ÷ total_rows) × 100",
    exampleEs: "Dataset de contratos con IDs repetidos → penalización de unicidad.",
    exampleEn: "Contracts dataset with repeated IDs → uniqueness penalty.",
    isoRef: "ISO/IEC 25012:2008 §4.18",
  },
  {
    id: "openness",
    nameEs: "Apertura",
    nameEn: "Openness",
    weight: WEIGHTS.openness,
    icon: "Unlock",
    descriptionEs: "Calificación de la licencia según el Open Definition: dominio público > CC-BY > CC-BY-SA > restrictiva.",
    descriptionEn: "License rating per the Open Definition: public domain > CC-BY > CC-BY-SA > restrictive.",
    formulaEs: "Dominio público=100, CC-BY=80, CC-BY-SA=60, Sin licencia=20",
    formulaEn: "Public domain=100, CC-BY=80, CC-BY-SA=60, No license=20",
    exampleEs: "Mayoría de datasets NL bajo licencia implícita → score promedio 60.",
    exampleEn: "Most NL datasets under implicit license → average score 60.",
    isoRef: "ISO/IEC 25012:2008 §4.16",
  },
  {
    id: "timeliness",
    nameEs: "Puntualidad",
    nameEn: "Timeliness",
    weight: WEIGHTS.timeliness,
    icon: "Clock",
    descriptionEs: "Actualidad del dataset medida por días transcurridos desde la última modificación.",
    descriptionEn: "Dataset currency measured by days elapsed since last modification.",
    formulaEs: "max(0, 100 − días_desde_actualización × 0.1)",
    formulaEn: "max(0, 100 − days_since_update × 0.1)",
    exampleEs: "Dataset con metadata_modified de ayer → score 99.9.",
    exampleEn: "Dataset modified yesterday → score 99.9.",
    isoRef: "ISO/IEC 25012:2008 §4.15",
  },
];

export const GRADE_CRITERIA = {
  gold: {
    threshold: 90,
    color: "gold",
    criteria: [
      { es: "Score global ≥ 90 / 100", en: "Global score ≥ 90 / 100" },
      { es: "Completitud ≥ 95%", en: "Completeness ≥ 95%" },
      { es: "URL activa y formato CSV/JSON", en: "Active URL and CSV/JSON format" },
      { es: "Metadata con título, descripción y organización", en: "Metadata with title, description, and organization" },
      { es: "Actualización en los últimos 90 días", en: "Updated within the last 90 days" },
    ],
  },
  silver: {
    threshold: 70,
    color: "silver",
    criteria: [
      { es: "Score global 70–89 / 100", en: "Global score 70–89 / 100" },
      { es: "Completitud ≥ 80%", en: "Completeness ≥ 80%" },
      { es: "URL activa (formato no restrictivo)", en: "Active URL (non-restrictive format)" },
      { es: "Metadata parcial (mínimo título y organización)", en: "Partial metadata (minimum title and organization)" },
      { es: "Actualización en los últimos 180 días", en: "Updated within the last 180 days" },
    ],
  },
  bronze: {
    threshold: 0,
    color: "bronze",
    criteria: [
      { es: "Score global < 70 / 100", en: "Global score < 70 / 100" },
      { es: "Completitud < 80% o valores nulos significativos", en: "Completeness < 80% or significant null values" },
      { es: "URL rota o formato propietario (PDF/XLSX sin alternativa)", en: "Broken URL or proprietary format (PDF/XLSX without alternative)" },
      { es: "Metadata insuficiente", en: "Insufficient metadata" },
      { es: "Sin actualización en más de 180 días", en: "No update in more than 180 days" },
    ],
  },
};
